
// NAVIGATION

export const TOGGLE_NAV_DRAWER = 'TOGGLE_NAV_DRAWER';

// RECIPIES
export const QUERY_RECIPES_SUCCESS = 'QUERY_RECIPES_SUCCESS';
export const LOAD_RECIPES_SUCCESS = 'LOAD_RECIPES_SUCCESS';
